//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMSHRv2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTimeOffset BirthDate { get; set; }
        public int Department_Id { get; set; }
        public int Salary { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
